title: <p align="center"> Amilcar Machacca</p>

logo: /assets/img/logo.png

description: <p align="center">ğŸ—ï¸ Structural Engineering </p>
  <p align="center">
  <a href="https://web.facebook.com/tommy.sllb">Facebook</a> |
  <a href="https://www.linkedin.com/in/amilcar-machacca-mayo-7635622a3/">LinkedIn</a>
  </p>
  
  <p align="justify">
  Estudiante de IngenierÃ­a Civil en el octavo semestre. Mi fascinaciÃ³n se centra en la ingenierÃ­a estructural, la programaciÃ³n y la geotecnia. Estoy comprometido con el aprendizaje constante y el desarrollo de habilidades en diversas Ã¡reas.
  <br><br>
  Poseo habilidades en Python, Revit, AutoCAD, Delphin Express y S10.
  <br><br>
  </p>
show_downloads: false

